name: Build and Release Installer

on:
  push:
    tags:
      - "v*" # Trigger workflow on tags, e.g., v1.0.0

permissions:
  contents: write # Ensure GITHUB_TOKEN has write permissions

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Extract Tag Version
        run: |
          tag_name=${GITHUB_REF#refs/tags/}
          version=${tag_name##v}
          echo "::set-env name=TAG_VERSION::$version"
      - name: Use the Tag Version
        run: echo "The current tag version is $TAG_VERSION"
