name: Build and Release Installer

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like "v1.0.0"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install NSIS
        run: |
          choco install nsis -y
        shell: powershell

      - name: Extract Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Project
        run: |
          dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true
        env:
          VERSION: ${{ env.VERSION }}

      - name: Generate Installer
        run: |
          makensis installer_script.nsi
        env:
          VERSION: ${{ env.VERSION }}

      - name: Upload Installer to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: SampleAppInstaller.exe
          asset_name: "SampleAppInstaller_v${{ env.VERSION }}.exe"
          content_type: application/octet-stream
