name: Build and Release Installer

on:
  push:
    tags:
      - "v*" # Trigger workflow on tags, e.g., v1.0.0

permissions:
  contents: write # Ensure GITHUB_TOKEN has write permissions

jobs:
  build:
    runs-on: windows-latest
    env: # Define global variables here
      VERSION: ""

    steps:
      - name: Extract Version from Tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV # Extracts the version part (e.g., 'v1.0.0')

      - name: Print Global Variable
        run: echo "Global Variable is ${{ env.VERSION }}" # Accesses the updated VERSION
        env:
          VERSION: ${{ env.VERSION }}
