name: Build and Release Installer

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        shell: powershell
        run: |
          $version = "${{ github.ref }}" -replace "refs/tags/v", ""
          echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8

      - name: Install NSIS
        shell: powershell
        run: choco install nsis -y

      - name: Generate NSIS Installer
        run: makensis installer_script.nsi

      - name: Rename Installer with Tag
        shell: powershell
        run: |
          $tag = $env:GITHUB_REF -replace '^refs/tags/', ''
          $tag = $tag -replace '^v', ''  # Remove leading 'v' if necessary
          Rename-Item -Path "SampleAppInstaller.exe" -NewName "SampleAppInstaller-$tag.exe"

      - name: List files (debug purposes)
        run: dir

      - name: Create a GitHub Release and upload the installer
        uses: softprops/action-gh-release@v2
        with:
          files: SampleAppInstaller-${{ env.VERSION }}.exe
          name: "SampleApp ${{ env.VERSION }}"
          tag_name: "v${{ env.VERSION }}"
          body: ${{ env.RELEASE_NOTES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
