name: Build and Release Installer

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Print GitHub username (actor)
        shell: powershell
        run: |
          $actor = "${{ github.actor }}"
          $repo = "${{ github.repository }}"
          Write-Host "GitHub username (actor): $actor"
          Write-Host "GitHub repository: $repo"
