name: Build and Release Installer

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        shell: powershell
        run: |
          $version = "${{ github.ref }}" -replace "refs/tags/v", ""
          echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8

      - name: Construct installer download link
        id: construct_link
        shell: powershell
        run: |
          $repo = "${{ github.repository }}"
          $version = "${{ env.VERSION }}"
          $url = "https://github.com/$repo/releases/latest/download/SampleAppInstaller-$version.exe"
          echo "DOWNLOAD_URL=$url" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8

      - name: Create a GitHub Release and upload the installer
        uses: softprops/action-gh-release@v2
        with:
          files: SampleAppInstaller-${{ env.VERSION }}.exe
          name: "SampleApp ${{ env.VERSION }}"
          tag_name: "v${{ env.VERSION }}"
          body: ${{ env.RELEASE_NOTES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README.md
        run: |
          DOWNLOAD_URL=${{ env.DOWNLOAD_URL }}
          sed -i "s|href=\"#\"|href=\"$DOWNLOAD_URL\"|" README.md
          sed -i "s|\\[here\\]()|[here]($DOWNLOAD_URL)|" README.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Update README.md with latest release URL"
