name: Build and Release Installer

on:
  push:
    tags:
      - "v*" # Trigger workflow on tags, e.g., v1.0.0

permissions:
  contents: write # Ensure GITHUB_TOKEN has write permissions

jobs:
  build:
    runs-on: windows-latest

    env: # Define global variables here
      GLOBAL_VARIABLE: "value for all steps"
    steps:
      - name: Print global variable
        run: echo "Global Variable ${GLOBAL_VARIABLE} ${{GLOBAL_VARIABLE}}"
