name: Build and Release Installer

on:
  push:
    tags:
      - "v*" # Trigger workflow on tags, e.g., v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install NSIS
        run: |
          choco install nsis -y
        shell: powershell

      - name: Extract Version from Tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV  # Extract version from the tag

      - name: Publish Project
        run: |
          dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true
        env:
          VERSION: ${{ env.VERSION }}

      - name: Generate Installer
        run: |
          makensis installer_script.nsi
        env:
          VERSION: ${{ env.VERSION }}

      - name: Create GitHub Release (Automatically)
        id: create_release
        run: |
          release_name="Release v${{ env.VERSION }}"
          release_body="Automated release for version ${GITHUB_REF#refs/tags/v}."
          response=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"tag_name\":\"v${{ env.VERSION }}\",\"name\":\"$release_name\",\"body\":\"$release_body\",\"draft\":false,\"prerelease\":false}" \
            "https://api.github.com/repos/${{ github.repository }}/releases")

          # Extract the upload_url from the response
          upload_url=$(echo $response | jq -r .upload_url)
          echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV

      - name: Upload Installer to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }} # Use the environment variable containing the upload_url
          asset_path: SampleAppInstaller.exe
          asset_name: "SampleAppInstaller_v${{ env.VERSION }}.exe"
          asset_content_type: application/octet-stream
