name: Build and Release Installer

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NSIS
        shell: powershell
        run: choco install nsis -y

      - name: Generate NSIS Installer
        run: makensis installer_script.nsi

      - name: Rename Installer with Tag
        shell: powershell
        run: |
          $tag = $env:GITHUB_REF -replace '^refs/tags/', ''
          $tag = $tag -replace '^v', ''  # Remove leading 'v' if necessary
          Rename-Item -Path "SampleAppInstaller.exe" -NewName "SampleAppInstaller-$tag.exe"

      - name: List files (debug purposes)
        run: dir
