name: Build and Release Installer

on:
  push:
    tags:
      - "v*" # Trigger workflow on tags, e.g., v1.0.0

permissions:
  contents: write # Ensure GITHUB_TOKEN has write permissions

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Extract release notes from CHANGELOG.md
      - name: Extract Release Notes
        id: extract_notes
        shell: powershell
        run: |
          $changelogPath = "CHANGELOG.md"
          $version = "${{ github.ref }}" -replace "refs/tags/v", ""

          Write-Output "Looking for release notes for version: $version"

          # Check if CHANGELOG.md exists
          if (-Not (Test-Path $changelogPath)) {
              Write-Error "CHANGELOG.md file not found at $changelogPath"
              exit 1
          }

          # Read the content of CHANGELOG.md
          $content = Get-Content $changelogPath -Raw

          # Regex pattern to extract notes for the current version
          $pattern = "(?s)(## \[$version\].*?)(?=## \[|\Z)"
          $matches = [regex]::Matches($content, $pattern)

          if ($matches.Count -eq 0) {
              Write-Output "No release notes found for version $version."
              echo "RELEASE_NOTES=" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8
          } else {
              $releaseNotes = $matches[0].Groups[1].Value.Trim()
              Write-Output "Extracted Release Notes: $releaseNotes" # Debug output
              
              # Use a delimiter to set a multi-line environment variable
              echo "RELEASE_NOTES<<EOF" | Out-File -Append -FilePath $Env:GITHUB_ENV
              echo "$releaseNotes" | Out-File -Append -FilePath $Env:GITHUB_ENV
              echo "EOF" | Out-File -Append -FilePath $Env:GITHUB_ENV
          }

      # Step 3: Build Project
      - name: Build Project
        run: dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true
        env:
          VERSION: ${{ env.VERSION }}

      # Step 4: Create GitHub Release and upload installer
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: SampleAppInstaller.exe # Replace with the actual installer file you want to upload
          name: "Release v${{ env.VERSION }}"
          tag_name: "v${{ env.VERSION }}"
          body: ${{ env.RELEASE_NOTES }} # Use the release notes extracted above
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
